# --- 1) 基本設定 ----------------------------------------------------------
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
locale: ja-JP
title: phalanx-hk blog
description: phalanx-hk's personal website.
url: "https://phalanx-hk.github.io/"

timezone: Asia/Tokyo

# --- 2) プラグイン --------------------------------------------------------
plugins:
  - jekyll-include-cache
  - jekyll-redirect-from

include:
  - _pages

# --- 3) 著者 --------------------------------------------------------------
author:
  name: Hirotoshi Kitamura
  avatar: /assets/images/avatar.jpg
  bio: "Software Engineer."
  location: Osaka, Japan
  links: &author_links
    - label: Twitter
      icon: fab fa-fw fa-twitter
      url: https://twitter.com/ZFPhalanx12345
    - label: GitHub
      icon: fab fa-fw fa-github-alt
      url: https://github.com/phalanx-hk
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/phalanx2021/
    - label: Kaggle
      icon: fab fa-fw fa-kaggle
      url: https://www.kaggle.com/phalanx
    - label: YOUTRUST
      icon: fas fa-fw fa-user-circle
      url: https://youtrust.jp/users/3e486e3b2154d87fc4a038fee3af27b0
    - label: Speaker Deck
      icon: fab fa-fw fa-speaker-deck
      url: https://speakerdeck.com/phalanx

footer:
  links: *author_links

# --- 4) Markdown / 抜粋 ---------------------------------------------------
excerpt_separator: "<!--more-->"
kramdown:
  hard_wrap: true

# --- 5) コレクション ------------------------------------------------------
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  tips:
    output: true
    permalink: /tips/:path/
  papers:
    output: true
    permalink: /papers/:path/

# --- 6) デフォルト値 -------------------------------------------------------
defaults:
  - values:
      layout: single
      header:
        teaser: /assets/images/teaser-1200x630.png
  - scope:
      path: ""
      type: posts
    values:
      classes: no-sidebar
      show_date: true
      toc: true
      toc_icon: list
      toc_sticky: true
      share: true
      related: true
  - scope:
      path: ""
      type: works
    values:
      classes: wide
      sidebar:
        - nav: works

# --- 7) スクリプト ---------------------------------------------------------
after_footer_scripts:
  - /assets/js/theme-toggle.js

# --- 8) その他 -------------------------------------------------------------
category_archive:
  type: liquid
  path: /archive/categories/
tag_archive:
  type: liquid
  path: /archive/tags/
